### PR TITLE
Release v4.0.0

### PR DESCRIPTION
**Pull request by KadoBOT**

### CODE REVIEW

**Comment by ohadbenita** [comment]
Thanks for the quick response on this @KadoBOTsteppypants-3oEjHZ0VV7sPH1CZAk

**Review by Aleffio — COMMENTED** [review]
please also update
https://github.com/Adyen/adyen-python-api-library/blob/develop/Adyen/settings.py#L15
with new version number

**Review by cyattilakiss — APPROVED** [review]

**Review by Aleffio — APPROVED** [review]

**Comment by ohadbenita** [comment]
@KadoBOT When should I expect to see it in PyPi?

**Comment by Aleffio** [comment]
Hi @ohadbenita it's up now: https://pypi.org/project/Adyen/

**Comment by ohadbenita** [comment]
Thanks, I appreciate it greatly.

**Pull request merged**
