### PR TITLE
Fix excluding files properly

### PR DESCRIPTION
**Pull request by jillingk**
**Description**

**Tested scenarios**

**Fixed issue**:

### CODE REVIEW

**Comment by karolyi** [comment]
Tested the fork locally, can confirm it works. Please merge and make a release at your earliest convenience.

**Review by DjoykeAbyah — APPROVED** [review]

**Comment by karolyi** [comment]
He who needs it, fixes it. A general rule of opensource. :)

**Comment by karolyi** [comment]
image
Say what?! You just re-release 12.4.0?

**Comment by DjoykeAbyah** [comment]
Hi @karolyi,

We were working on publishing our releases to PyPI now that our pipeline has been fixed. This temporarily caused some releases on GitHub to appear out of order—apologies for the confusion. This should be resolved now.

I also wanted to let you know that our latest release includes the fix that you and @jillingk have been working on!

Kind regards,
Djoyke
Adyen

**Pull request merged**
